language: node_js
sudo: required
node_js: 12
services:
  - docker
script:
  - docker build -t $DOCKER_USERNAME/$HEROKU_APP_NAME -f Dockerfile .
after_success:
  - docker tag $DOCKER_USERNAME/$HEROKU_APP_NAME registry.heroku.com/$HEROKU_APP_NAME/web
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
deploy:
  provider: script
  script:
    docker push $DOCKER_USERNAME/$HEROKU_APP_NAME; docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  on:
    branch: main
notifications:
  slack:
    rooms:
      - secure: iCtZVSZQIbZIkCON1OZqMhIFB5MSnh1cc1G3bA29p0UewHZXX6Br5O1Cvv1I/hdsXKYBGPcUqEHHVDMPoH4g8HgGeUdty6m/2nFIW0SbRMCvNjLH6T1Kfqe0O3PM4k0UjG1zmZN1ZrYHKWVAk7Cz2JlKfDX52c3V5Qlf4LbXzI3wtlkgMv6Jjj0ahIip9dYazyQJ2CYse17xwo5AsTcv1thCWOWHiguX8c/JC6aTSLOeULYX/ezQmAH/CN2cKfe2kWoW6If8iTS5dGHNbn3mg9QaDEw9w7/GuaJEFCYBeV3PDYlDV0vHYHCCYq5a+CodaF8InrSid0wrwLvY8+y/an92rokOMI1DxaDFZKH+l2tU9lhYW1lxzF+Ytbn2PAiM2V4aLhu6rsYP8ErMdBsEQj741QFLDqJAjvJ4EDAg+Fhq7mVlsdGCTxANOXB+KZOUAB4I7XpI8kkfTznAdUMkttQV74EzmVs2wa9l6FKTItNP+4osDfCN/k0fvSEbRS6NHDU3e7VDOXdEn2KyvMr1K9oW7m33MQXXYWy7csx0LYK3zoGnafKdrICet35TRN+6WiTLRkMQXz8h7Qh7ykg3/mKQ1aMUzxRDpC9HTgj3rKgALFqJztbsh6xmVq4A9kNxul4xtMCksAdnRhGPujuyNos+eDBjMApEgzWb9tZJDjQ=
