language: node_js
sudo: required
node_js: 12
services:
  - docker
script:
  - docker build -t $DOCKER_USERNAME/$HEROKU_APP_NAME -f Dockerfile .
after_success:
  - docker tag $DOCKER_USERNAME/$HEROKU_APP_NAME registry.heroku.com/$HEROKU_APP_NAME/web
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
deploy:
  provider: script
  script:
    docker push $DOCKER_USERNAME/$HEROKU_APP_NAME; docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  on:
    branch: main
notifications:
  slack:
    rooms:
      secure: fWlbSvRQCTG3FvSRmuw9YSP3M+2DK+c27/5xDOK5OryUM7lPMM7rLGreWhJKD6FDxSBrkuApZWoOtkgiXLRMzamTRBe4oImaTr7V4+IULcQGoPSEdsMZR0uzG89DmsfCfnlFyVgAiFPEuJ/RtrFkvu4T3otrOmf0vYyzVap4cRjOIFzZzwFVu4nGJfxFfRr3tNktRkUJ7iOfPj78Lz6JSjGUDVxCHrzWGdjDFFAZPjR5lvq85pO4Jiu0WFSN8x6Jgh04I8M1X1q+2wU7sMAonGQ+wbWVRxm1jcppUZw7tXku0Fwbj7wrXZVrCJOt9KWoCjJ1VyXXpAvdPwGGHrfruxd7Y+eRWzC5p9prQrCB6bZMPm0i1MUzolrrI9cqGE4jldkNkaux552+88BOjXJjgZFYQW2bu5CZd9XlaaRNREp4qzTC1iy7kGAKUcB/RzHT9FF0CzbOvm+aKKjM1W6DH5dFMz9IpLNZ2ktG5/Wdv2SyyLXb6S+bjqSEOjOo3sTnMWT9Bw89VR7+iqRbf7k8bxbSgbH0bOjYGNat6IifSNJWublX2G/2zf1K1o4kIrfjtjGap9dRHG92uo92+9wRSHxqqkoEoi8+qcCdPXggMZOh7JXH5whdEGB4rtG6Sb5Mvz27ZNhQhGO8RSgGP8ZcjtXD1RPllGhoHJbCSoYRrIo=
