language: node_js
sudo: required
node_js: 12
services:
  - docker
script:
  - docker build -t $DOCKER_USERNAME/$HEROKU_APP_NAME -f Dockerfile .
after_success:
  - docker tag $DOCKER_USERNAME/$HEROKU_APP_NAME registry.heroku.com/$HEROKU_APP_NAME/web
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
deploy:
  provider: script
  script:
    docker push $DOCKER_USERNAME/$HEROKU_APP_NAME; docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  on:
    branch: main
notifications:
  slack:
    rooms:
      - secure: IOW0SMUUrehXnznc4n5DF2NCmoDuWxxYx60HAYvcuh3rCToE2OKg3iG6kZv9uc7tc8iNw15IqhOIxWIs/flLz8XiJVy8eZvap+j+g9kz1Y8NaXXsgH/wnaQip8yVrC25gOr1JpmSikdVdBPOZW7U2sPQpz73nfSUQgt2YHjonjNRFSsOAGWIpoMUyM+vg2hpL5EphH5+emzyvJjqB5CA8k2n6dABccOeeWoe7z5GoqYSOVeDmlZVqq9ZT6nJXXE2LBt44W0C5sFFHx8O4pK8kOTvlS+H5GpAq5twE6hkdC8VwE8CKtDxgQolGsopGFfTlZtiaW4bMkwjedNxT0cWv66i32FPRfz4jIxWM4I1EVUz8Bu8LSrf2faCyoKpNOoU1LJHE0awyhOWol5JrQuBba9JfQGMjQMTA09Y8f0c/v5jM1WiuUh98bHOpGorH7LPOGDRjRMjlPxplez8iU/0NryLYybvTWFBojDDDNOkN8LiNCF0RI3rctzym9af7J4+QoApSqleNhGSGrEeVICCjGoXWFO09Db6uG0jPAooevWs4qXfzO2Cz00GYySFNUpYRIVzHZD54Nh5y4rV9N91GDcTWbKRT5sPib5gr+iAP0zT8pxikVe0u3pNEE+EnzjchfYXpwitRNGk2ACGBm7ffnh5yk2+zRt3Fktav6R8jAs=
    on_success: always # change: send a notification when the build status changes.
    on_failure: always # always: always send a notification.
